// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBeh6m_eeseRzDneONN8LoqkvCMkCQcp4E',
    appId: '1:326557431629:web:30b0ac63b286afa6cea904',
    messagingSenderId: '326557431629',
    projectId: 'posthub-7f739',
    authDomain: 'posthub-7f739.firebaseapp.com',
    storageBucket: 'posthub-7f739.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2e2sjnzdSlf7ahIpL4FLSPforbVO3g-o',
    appId: '1:326557431629:android:b29220e72823aea3cea904',
    messagingSenderId: '326557431629',
    projectId: 'posthub-7f739',
    storageBucket: 'posthub-7f739.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0TXiSmfFGJnBzbmv2zE8ZI8cz4w3ScXc',
    appId: '1:326557431629:ios:92fed065e2f8f16bcea904',
    messagingSenderId: '326557431629',
    projectId: 'posthub-7f739',
    storageBucket: 'posthub-7f739.appspot.com',
    iosClientId: '326557431629-d3qi5kjh2lqf1e42634q3gjt494kgavb.apps.googleusercontent.com',
    iosBundleId: 'com.example.posthub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0TXiSmfFGJnBzbmv2zE8ZI8cz4w3ScXc',
    appId: '1:326557431629:ios:74b02e6dd8c95ac2cea904',
    messagingSenderId: '326557431629',
    projectId: 'posthub-7f739',
    storageBucket: 'posthub-7f739.appspot.com',
    iosClientId: '326557431629-k5eq6t5lbdc1p8n9c3ptsbdbkamnmvil.apps.googleusercontent.com',
    iosBundleId: 'com.example.posthub.RunnerTests',
  );
}
